name: Deploy via SSM

on:
  workflow_dispatch

jobs:
  start:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Deploy to test server
        uses: peterkimzz/aws-ssm-send-command@master
        id: ssm
        with:
          aws-region: eu-central-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          instance-ids: ${{ secrets.INSTANCE_ID }}

          working-directory: /home/django
          command: /bin/bash ./deploy.sh > deployment.log 2>&1

